### ISSUE TITLE
project with both GroovyPlugin and JavaPlugin

### ISSUE THREAD

**Issue by chenrui333** [rapidminer/gradle-plugin-rapidminer-code-quality#1]
I saw the plugin handles Groovy and Java separately [ref](https://github.com/rapidminer/gradle-plugin-rapidminer-code-quality/blob/master/src/main/groovy/com/rapidminer/gradle/RapidMinerCodeQualityPlugin.groovy#L83-L115), what if a project contains both Groovy code and Java code?

**Comment by ncwoehler** [comment]
You are right. Probably it is a good idea to remove the `else` there. Even though we actually never really use the `codenarc` plugin :-)
